# ⚽ YAGO VIBE PWA - Netlify 배포 설정
[build]
  # 빌드 명령어
  command = "npm run build"
  # 빌드 결과물 디렉토리
  publish = "dist"
  # Functions 디렉토리 (Firebase Functions 사용 시)
  functions = "netlify/functions"

# SPA 라우팅을 위한 리다이렉트 설정
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers 설정 (PWA 최적화)
[[headers]]
  for = "/*"
  [headers.values]
    # PWA 캐싱 최적화
    Cache-Control = "public, max-age=0, must-revalidate"
    # 보안 헤더
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"

# Service Worker는 캐시하지 않음
[[headers]]
  for = "/sw.js"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"
    Service-Worker-Allowed = "/"

# Manifest는 캐시 허용
[[headers]]
  for = "/manifest.webmanifest"
  [headers.values]
    Cache-Control = "public, max-age=31536000"
    Content-Type = "application/manifest+json"

# 아이콘 파일들 캐시
[[headers]]
  for = "/icons/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

# 환경 변수 설정 (예시)
[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"

# 배포 후 처리
[build.processing]
  skip_processing = false

# 브랜치별 배포 설정
[context.production]
  command = "npm run build"
  publish = "dist"

[context.deploy-preview]
  command = "npm run build"
  publish = "dist"

[context.branch-deploy]
  command = "npm run build"
  publish = "dist"
