import React, { useEffect, useState } from "react";
import { db } from "../lib/firebase";
import { collection, query, where, orderBy, getDocs, Timestamp } from "firebase/firestore";
import { jsPDF } from "jspdf";

export default function AdminReportPDF() {
  const [summaries, setSummaries] = useState<any[]>([]);
  const [period, setPeriod] = useState<"week" | "month">("week");
  const [loading, setLoading] = useState(false);

  const fetchSummaries = async () => {
    setLoading(true);
    try {
      const now = new Date();
      const daysAgo = period === "week" ? 7 : 30;
      const from = new Date(now.getTime() - daysAgo * 24 * 60 * 60 * 1000);
      
      const q = query(
        collection(db, "chat_summaries"),
        where("createdAt", ">=", Timestamp.fromDate(from)),
        orderBy("createdAt", "desc")
      );
      
      const snap = await getDocs(q);
      const data = snap.docs.map((d) => ({ id: d.id, ...d.data() }));
      setSummaries(data);
      console.log(`??${period} ë¦¬í¬???°ì´??${data.length}ê°?ë¡œë“œ`);
    } catch (error) {
      console.error("???°ì´??ë¡œë“œ ?¤ë¥˜:", error);
      alert("?°ì´?°ë? ë¶ˆëŸ¬?¤ëŠ” ì¤??¤ë¥˜ê°€ ë°œìƒ?ˆìŠµ?ˆë‹¤.");
    } finally {
      setLoading(false);
    }
  };

  const generatePDF = () => {
    const doc = new jsPDF();
    
    // ?œëª©
    doc.setFontSize(20);
    doc.text("YAGO VIBE AI Report", 20, 20);
    
    doc.setFontSize(12);
    doc.text(`Report Period: ${period === "week" ? "Last 7 days" : "Last 30 days"}`, 20, 30);
    doc.text(`Generated: ${new Date().toLocaleDateString("ko-KR")}`, 20, 37);

    // ê°ì • ?µê³„
    const positive = summaries.filter((s) => {
      const sent = s.sentiment || s.emotion || "";
      return sent.toLowerCase() === "positive" || sent === "ê¸ì •";
    }).length;
    const neutral = summaries.filter((s) => {
      const sent = s.sentiment || s.emotion || "";
      return sent.toLowerCase() === "neutral" || sent === "ì¤‘ë¦½";
    }).length;
    const negative = summaries.filter((s) => {
      const sent = s.sentiment || s.emotion || "";
      return sent.toLowerCase() === "negative" || sent === "ë¶€??;
    }).length;
    const total = summaries.length || 1;

    doc.setFontSize(14);
    doc.text("========================================", 20, 47);
    doc.text("Sentiment Statistics", 20, 55);
    doc.text("========================================", 20, 62);
    
    doc.setFontSize(12);
    doc.text(`Positive: ${positive} (${(positive / total * 100).toFixed(1)}%)`, 20, 72);
    doc.text(`Neutral: ${neutral} (${(neutral / total * 100).toFixed(1)}%)`, 20, 80);
    doc.text(`Negative: ${negative} (${(negative / total * 100).toFixed(1)}%)`, 20, 88);
    doc.text(`Total Messages: ${total}`, 20, 96);

    // ì£¼ìš” ?”ì•½
    doc.setFontSize(14);
    doc.text("========================================", 20, 110);
    doc.text("Top Summaries", 20, 118);
    doc.text("========================================", 20, 125);

    let y = 135;
    summaries.slice(0, 15).forEach((s, i) => {
      if (y > 270) {
        doc.addPage();
        y = 20;
      }

      const sentimentLabel = 
        (s.sentiment || s.emotion || "neutral").toLowerCase() === "positive" ? "[+]" :
        (s.sentiment || s.emotion || "neutral").toLowerCase() === "negative" ? "[-]" : "[=]";

      const text = `${i + 1}. ${sentimentLabel} ${s.summary || "No summary"}`;
      const lines = doc.splitTextToSize(text, 170);
      
      doc.setFontSize(10);
      doc.text(lines, 20, y);
      y += lines.length * 6 + 3;
    });

    // ?¸í„°
    doc.setFontSize(8);
    doc.text("Generated by YAGO VIBE AI System", 20, 285);
    doc.text(`Page 1 of ${doc.getNumberOfPages()}`, 170, 285);

    // ?€??    const filename = `YAGO_Report_${period}_${new Date().toISOString().slice(0, 10)}.pdf`;
    doc.save(filename);
    console.log(`??PDF ?ì„± ?„ë£Œ: ${filename}`);
  };

  useEffect(() => {
    fetchSummaries();
  }, [period]);

  return (
    <div className="min-h-screen bg-gray-50 pb-20">
      <div className="max-w-4xl mx-auto p-6">
        {/* ?¤ë” */}
        <div className="text-center mb-8">
          <h2 className="text-3xl font-bold text-gray-900 mb-2">?“… ì£¼ê°„Â·?”ê°„ ë¦¬í¬???ì„±ê¸?/h2>
          <p className="text-gray-600">AI ?€???”ì•½??PDFë¡??¤ìš´ë¡œë“œ?˜ì„¸??/p>
        </div>

        {/* ê¸°ê°„ ? íƒ */}
        <div className="flex justify-center gap-4 mb-8">
          <button
            onClick={() => setPeriod("week")}
            className={`px-6 py-3 rounded-xl font-semibold transition-all ${
              period === "week"
                ? "bg-blue-600 text-white shadow-lg scale-105"
                : "bg-white border border-gray-300 text-gray-700 hover:bg-gray-50"
            }`}
          >
            ?“… ì£¼ê°„ ë¦¬í¬??          </button>
          <button
            onClick={() => setPeriod("month")}
            className={`px-6 py-3 rounded-xl font-semibold transition-all ${
              period === "month"
                ? "bg-blue-600 text-white shadow-lg scale-105"
                : "bg-white border border-gray-300 text-gray-700 hover:bg-gray-50"
            }`}
          >
            ?“† ?”ê°„ ë¦¬í¬??          </button>
        </div>

        {/* ?µê³„ ì¹´ë“œ */}
        <div className="grid grid-cols-3 gap-4 mb-8">
          <div className="bg-white p-4 rounded-xl shadow-md text-center">
            <p className="text-sm text-gray-500 mb-1">ë¶„ì„ ë©”ì‹œì§€</p>
            <p className="text-2xl font-bold text-gray-900">{summaries.length}ê°?/p>
          </div>
          <div className="bg-white p-4 rounded-xl shadow-md text-center">
            <p className="text-sm text-gray-500 mb-1">ê¸ì • ë¹„ìœ¨</p>
            <p className="text-2xl font-bold text-green-600">
              {summaries.length > 0
                ? ((summaries.filter(s => (s.sentiment || s.emotion || "").toLowerCase().includes("positive") || (s.sentiment || s.emotion || "").includes("ê¸ì •")).length / summaries.length) * 100).toFixed(1)
                : 0}%
            </p>
          </div>
          <div className="bg-white p-4 rounded-xl shadow-md text-center">
            <p className="text-sm text-gray-500 mb-1">ê¸°ê°„</p>
            <p className="text-lg font-bold text-blue-600">
              {period === "week" ? "7?? : "30??}
            </p>
          </div>
        </div>

        {/* PDF ?ì„± ë²„íŠ¼ */}
        <div className="text-center mb-8">
          <button
            onClick={generatePDF}
            disabled={loading || summaries.length === 0}
            className="px-8 py-4 bg-gradient-to-r from-green-500 to-emerald-600 text-white rounded-2xl font-bold text-lg hover:from-green-600 hover:to-emerald-700 transition-all shadow-lg hover:shadow-xl disabled:opacity-50 disabled:cursor-not-allowed"
          >
            {loading ? "ë¡œë”© ì¤?.." : summaries.length === 0 ? "?°ì´???†ìŒ" : "?“„ PDF ?¤ìš´ë¡œë“œ"}
          </button>
          <p className="text-xs text-gray-500 mt-2">
            {period === "week" ? "ìµœê·¼ 7?¼ê°„" : "ìµœê·¼ 30?¼ê°„"} {summaries.length}ê°œì˜ ?”ì•½???¬í•¨?©ë‹ˆ??
          </p>
        </div>

        {/* ë¯¸ë¦¬ë³´ê¸° */}
        <div className="bg-white p-6 rounded-2xl shadow-md">
          <h3 className="text-xl font-semibold mb-4 text-center">?“ ë¯¸ë¦¬ë³´ê¸°</h3>
          {summaries.length === 0 ? (
            <p className="text-center text-gray-400 py-10">
              {period === "week" ? "ìµœê·¼ 7?¼ê°„" : "ìµœê·¼ 30?¼ê°„"} ë¶„ì„???€?”ê? ?†ìŠµ?ˆë‹¤.
            </p>
          ) : (
            <div className="space-y-3 max-h-96 overflow-y-auto">
              {summaries.slice(0, 10).map((s, i) => {
                const sentiment = s.sentiment || s.emotion || "neutral";
                const sentimentKey = sentiment.toLowerCase();
                const isPositive = sentimentKey.includes("positive") || sentiment === "ê¸ì •";
                const isNegative = sentimentKey.includes("negative") || sentiment === "ë¶€??;

                return (
                  <div key={s.id} className="p-3 border-l-4 rounded-lg bg-gray-50"
                    style={{
                      borderLeftColor: isPositive ? "#4ade80" : isNegative ? "#f87171" : "#60a5fa"
                    }}
                  >
                    <div className="flex items-center gap-2 mb-1">
                      <span className="text-sm font-bold text-gray-400">#{i + 1}</span>
                      <span className="text-xs text-gray-500">
                        {s.createdAt?.toDate
                          ? new Date(s.createdAt.toDate()).toLocaleDateString("ko-KR")
                          : "? ì§œ ?•ë³´ ?†ìŒ"}
                      </span>
                      <span className={`text-xs px-2 py-0.5 rounded-full font-semibold ml-auto ${
                        isPositive ? "bg-green-100 text-green-700" :
                        isNegative ? "bg-red-100 text-red-700" :
                        "bg-blue-100 text-blue-700"
                      }`}>
                        {isPositive ? "?˜Š" : isNegative ? "?˜”" : "?˜"}
                      </span>
                    </div>
                    <p className="text-sm text-gray-800">{s.summary}</p>
                  </div>
                );
              })}
            </div>
          )}
        </div>
      </div>
    </div>
  );
}

