name: CI – E2E (Playwright)
on:
  push:
    paths: ["src/**","public/**","tests/**",".github/workflows/e2e.yml","playwright.config.ts","package.json"]
  workflow_dispatch:

jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v4
        with: { node-version: 20, cache: npm }
      - run: npm ci
      - run: npx playwright install --with-deps
      - name: Start dev server
        run: |
          (npm run dev -- --port 5173 > /dev/null 2>&1 &) 
          for i in {1..60}; do curl -fsS http://127.0.0.1:5173 && break || sleep 1; done
      - name: Run E2E
        env:
          E2E_BASE_URL: http://127.0.0.1:5173
        run: npx playwright test --reporter=line
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report
          if-no-files-found: ignore
